version: "3.8"

services:
  react-app:
    container_name: internal-erp-prod
    image: internal-erp-prod
    build:
      context: .
      target: production
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
