export enum FILE_UPLOAD_ACTIONS  {
    BULK_UPLOAD_PRODUCTS = 1,
    BULK_UPDATE_PRODUCTS = 2,
    BULK_UPDATE_LOCATION_PRICES_STOCK = 3,
    BULK_UPDATE_PRODUCT_LANGUAGE = 4,
    BULK_UPDATE_PRODUCT_DISPLAY_PRIORITY = 5, 
    CUSTOMER_SKU_ASSIGNMENT = 6,
    UPDATE_SEARCH_TERMS = 7,
    BULK_LINK_PRODUCTS = 8,
    BULK_DYNAMIC_PRICE_CREATE = 9,
    BULK_UPLOAD_PRODUCTS_TAX_GROUPS=10,
    NO_ACTION = -1,
}
